### ISSUE TITLE
Missing optimum(s) for WModel and NKL problems

### ISSUE THREAD

**Issue by jdreo** [IOHprofiler/IOHexperimenter#122]
WModel and NKLandscapes problems are missing known optima computation.

I remind that it was possible to deduce them by simple computations from the configuration and add the results in `objective_` at construction, but this is currently missing.

This information is however crucial for using correctly the Empirical Attainment loggers, without it, it is probably a far less useful feature.

**Comment by jdreo** [comment]
Incidentally, this may not be a very big problem, but I keep being puzzled by the term `objective` which in the code really means `optimum`. Is there a reason for this choice and would be a big burden to change it?

**Comment by jacobdenobel** [comment]
@FurongYe do you know if it is possible to get the optima for NKL problems?

**Comment by jacobdenobel** [comment]
For NKL problems it is not possible to get the optima, so closing this for now
