### ISSUE TITLE
Problem with pip install ioh

### ISSUE THREAD

**Issue by Rens-byte** [IOHprofiler/IOHexperimenter#135]
Dear sir/ madam,

I got an error when I was trying to download the latest version of ioh. This error disappeared when I downloaded the second latest version. Do you know how to solve this?

Kind Regards,
Rens

![Ioh_error](https://user-images.githubusercontent.com/74368041/159953884-cdfb6227-f680-49a9-aa38-85c0d18290a1.png)

**Comment by jacobdenobel** [comment]
Adressed in #141
