### ISSUE TITLE
IOH package installation

### ISSUE THREAD

**Issue by FurongYe** [IOHprofiler/IOHexperimenter#140]
Description: Errors on installing IOH python package.

Versions: 0.3.2.7.2

Steps to Reproduce: running 'python -m pip install IOH'

Actual Behavior: The package can not be installed successfully. 
<img width="1433" alt="WX20220420-105050@2x" src="https://user-images.githubusercontent.com/13196765/164191729-cb54df7d-2b1d-489f-b4e8-9627e263b28c.png">

**Comment by jacobdenobel** [comment]
Addressed in #141
