### ISSUE TITLE
failed to clone the fmt file

### ISSUE THREAD

**Issue by a1798441** [IOHprofiler/IOHexperimenter#154]
Hello all
I'm trying to install the IOHexperimenter onto my fedora linux machine and its having issues with cloning in the fmt 

Cloning into '/path/IOHexperimenter/external/fmt'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:fmtlib/fmt' into submodule path '/pathIOHexperimenter/external/fmt' failed
Failed to clone 'external/fmt'. Retry scheduled

it then tries again as scheduled and still fails

I just wanted to know if anyone else had similar issues and if they knew a fix

**Comment by jacobdenobel** [comment]
Hi [a1798441](https://github.com/a1798441),

This is an issue with your git configuration, not with the iohexperimenter package. What you can try is replacing the urls with their respective https variants, or to properly setup your git account with security keys [common issues here](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey).
