### ISSUE TITLE
Difference between `problem.state.optimum_found` in ioh and `problem.final_target_hit` in cocoex (BBOB functions)

### ISSUE THREAD

**Issue by reasonablecow** [IOHprofiler/IOHexperimenter#196]
Hi,

Does `problem.state.optimum_found` evaluate to true only if the optimum values are equal up to their precision?

I am experimenting with BBOB functions from both `ioh` and `cocoex` python libraries. To check if the problem was solved, with `ioh`, I use `problem.state.optimum_found`, and with `cocoex`, I use `problem.final_target_hit`. However, it seems that the two behave differently.

I tried to look it up, and it seems you [compare the exact values](https://github.com/IOHprofiler/IOHexperimenter/blob/master/include/ioh/problem/structures.hpp#L253-L254), while cocoex [adds a 1e-8 tolerance](https://github.com/numbbo/coco/blob/master/code-experiments/src/coco_problem.c#L443-L444).

Since I am using the Python interfaces, and both snippets I found are in the underlying C/C++ codes, I might be off. However, if you compare the number up to its precision, I thought I could use:
```py
problem.optimum.y + 1e-8 >= problem.state.current_best.y
```
instead of `problem.state.optimum_found`, and it should work the same as cocoex, right?

Thank you for your reply, and sorry if it's documented somewhere.

**Comment by jacobdenobel** [comment]
Hi, you are right,  `optimum_found` only evaluates to true whenever the optimum is precisely reached (given floating point rounding). For implementing a stopping using a given target precision, you would indeed have to implement custom criteria as you already give the example. The reason why this is implemented, and not using a fixed target of 1e-8 for example, is the fact that we allow a more flexible setup, that allows the user to implement their own functions. Those might have a different tolerance, deviating from the targets that coco uses.

I should point out that your example is only true for minimization, but I assume that is what you are interested in.

**Comment by reasonablecow** [comment]
Thank you for your response.
