### ISSUE TITLE
Package fails on import

### ISSUE THREAD

**Issue by samfux84** [IOHprofiler/IOHexperimenter#200]
Hi,

I have installed ioh 0.3.14 with pip for Python 3.10.2 and the package immediately fails on import:

```
[sfux@eu-login-06 ~]$ module list

Currently Loaded Modules:
  1) StdEnv   2) gcc/8.2.0   3) openblas/0.3.20   4) python/3.11.2



[sfux@eu-login-06 ~]$ pip install ioh
Collecting ioh
  Downloading ioh-0.3.14.tar.gz (772 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.3/772.3 kB 17.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /cluster/apps/nss/gcc-8.2.0/python/3.11.2/x86_64/lib64/python3.11/site-packages (from ioh) (1.23.5)
Building wheels for collected packages: ioh
  Building wheel for ioh (pyproject.toml) ... done
  Created wheel for ioh: filename=ioh-0.3.14-cp311-cp311-linux_x86_64.whl size=945539 sha256=d5b9fa830e848c6d3d7e526b74b1e5bdec04d9d9403a7e6149f85bc757bd61c3
  Stored in directory: /cluster/home/sfux/.cache/pip/wheels/8a/3f/cb/c365382b9980cc5aa437fe31339004f07fa32bd6126c020456
Successfully built ioh
Installing collected packages: ioh
Successfully installed ioh-0.3.14

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[sfux@eu-login-06 s~]$ python
Python 3.11.2 (main, Apr 14 2023, 09:06:29) [GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ioh
terminate called after throwing an instance of 'std::experimental::filesystem::v1::__cxx11::filesystem_error'
  what():  filesystem error: status: Permission denied [/cluster/home/IOHexperimenter/static]
Aborted
```

I run the Python interpreter from my home directory /cluster/home/sfux. Under /cluster/home, there is an automounter running that mounts the cluster users home directory. To me it looks like this is caused by some sort of path traversing, first checking

/cluster/home/sfux/IOHexperimenter/static

that then next checks

/cluster/home/IOHexperimenter/static

and then the automounter kicks in, because there is no user directory to be mounted under IOHexperimenter, which then causes the error message, but I am not 100% sure about this.

Do you have any idea how this issue can be resolved?

Best regards

Sam

**Comment by benjamc** [comment]
Package crashes upon import on cluster.
MWE:
```bash
python -c "import ioh"
```
results in 
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Cannot reshape vector into matrix of n * m
Aborted (core dumped)
```

System/Versions: 
```
python 3.10.14
ioh 0.3.15
Linux xxxx 4.18.0-477.51.1.el8_8.x86_64 #1 SMP Fri Mar 1 11:21:44 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Using `ioh==0.3.14` works.

**Comment by jacobdenobel** [comment]
Hi, 

You are both experiencing a similar error, which the same thing might fix. The package cannot find the location of some static files required to load some problem data, which you can set explicitly. Namely, by setting the environment variable `IOH_RESOURCES` to the path of the static folder (i.e. the unpacked static.tar.gz in the github repo). Then you should be able to run (version 3.15):
```bash
IOH_RESOURCES=/path/to/static python -c "import ioh"
```
Without any issues

@benjamc You are experiencing a bug introduced in version 0.3.15, which only looks at this environment variables, so if it is unset it will load the files incorrectly. We will fix this in the next release.

Hope this helps

**Comment by samfux84** [comment]
@jacobdenobel Thank you for your help. I can confirm that setting the environment variable solves the issue (I have installed ioh version 0.3.15):

```
[sfux@eu-login-16 ~]$ module load gcc/8.2.0 python/3.11.2

The following have been reloaded with a version change:
  1) gcc/4.8.5 => gcc/8.2.0



[sfux@eu-login-16 ~]$ export IOH_RESOURCES=/cluster/apps/nss/gcc-8.2.0/python/3.11.2/x86_64/lib64/python3.11/site-packages/ioh/static
[sfux@eu-login-16 ~]$ python
Python 3.11.2 (main, Apr 14 2023, 09:06:29) [GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ioh
>>>
```

**Comment by samfux84** [comment]
Please feel free to close this issue

**Comment by benjamc** [comment]
I can also confirm that `IOH_RESOURCES=/scratch/hpc-prf-intexml/cbenjamins/.conda/envs/carpsexp/lib/python3.10/site-packages/ioh/static/ python -c "import ioh"` works, thanks for your help :)

**Comment by benjamc** [comment]
I can also confirm that `IOH_RESOURCES=/.../lib/python3.10/site-packages/ioh/static/ python -c "import ioh"` works, thanks for your help :)
