### ISSUE TITLE
observer call interface

### ISSUE THREAD

**Issue by nojhan** [IOHprofiler/IOHexperimenter#29]
As of today, the only logger class (`IOHprofiler_csv_logger`) is documented to be actually called with `logger.write_line(…)`.

However, its base class (`IOHprofiler_observer`) do not expose such a call interface.

Consequently, it is not actually possible to declare a generic binding to any (future) class of observer.

I suggest to add a generic call interface, like `virtual void IOHprofiler_observer::log(const std::vector<double> &logger_info) = 0;` and replace `write_line` in examples.

**Comment by FurongYe** [comment]
Thanks for the suggestion. The idea is great! We will consider and finish it in this week.

**Comment by nojhan** [comment]
Proposed in PR #44
