### ISSUE TITLE
[3d party] headers inclusion scheme

### ISSUE THREAD

**Issue by nojhan** [IOHprofiler/IOHexperimenter#32]
While implementing a third party solver that use IOH as a problem provider (along with using logging), I faced the following problems (based on the developing branch, as of commit e46996f).

Problem: the header inclusion scheme makes it very painful to include the necessary files. Every include in the source expects a relative flat hierarchy, while the sources are deeply nested.

In order to be able to easily include from third party app, we would need to `#include <IOH/Template/problem.hpp>`. Having a sub-directory avoid file name collision.

To achieve that, I see two easy ways:

- either use an "installation" scheme, and add an installation target that copy the headers hierarchy in some location, containing an "IOH" directory (think `/usr/local/include/IOH/…`).
- either use a "framework" scheme, and rename the current "src" directory to "IOH" (or IOHexperimenter, of course). That way, third party apps just have to `include_dir` the root dir and `#include <IOH/…>` in their source.

Of course, one can do both.

**Comment by nojhan** [comment]
Also, having separate header and implementation would ease browsing the API.

For instance, a `header.h` can contain only a forward declaration of templates (along with the docstrings) and include the `header.hpp`, which contains the implementation.

**Comment by jacobdenobel** [comment]
Closing this, since we decided to go for a header-only scheme
