### ISSUE TITLE
[3d party] namespaces and class names

### ISSUE THREAD

**Issue by nojhan** [IOHprofiler/IOHexperimenter#33]
While implementing a third party solver that use IOH as a problem provider (along with using logging), I faced the following problems (based on the developing branch, as of commit e46996f).

All the classes are prefixed with `IOHprofiler`. Many methods are also prefixed, giving some cumbersome calls, like `IOH_problem* bench = new BBOB_suite; auto bench_problems = bench->IOHprofiler_suite_get_problems();`.

It would be more intuitive for a new user (at least to me) to use namespaces and avoid member names prefixed with the class name: `ioh::Suite* bench = new ioh::suite::BBOB; auto bench_problems = bench->get_problems();`. As a plus, this gives the opportunity to `using namespace ioh;` if concision is wanted.

**Comment by jacobdenobel** [comment]
This is also taken care of in branch: restructure

**Comment by nojhan** [comment]
Awesome!
