### ISSUE TITLE
Explicit interface contracts

### ISSUE THREAD

**Issue by nojhan** [IOHprofiler/IOHexperimenter#46]
It's somehow difficult to infer what is the contract that additional features should implement in the generic interfaces. If someone want to add a new problem to IOH, this renders the exercise more complicated.

For instance, the `IOHprofiler_problem` class has virtuals functions, but the `internal_call` is not pure virtual, and raise an error if called. An elegant implementation followings C++ coding style would be to remove the useless implementation and makes it `= 0`.

Additionally, it is not clear if some part of the interface is mandatory or not. For instance, the `prepare_problem` function is virtual, but no documentation indicates what is expected with it.

An improvement would be to use abstract classes, so as to makes clear and enforce the intended interfaces of the classes in the Template directory.
I suggest that the expected interface functions are moved at the beginning of the headers, with documentation explaining what is expected.

**Comment by wangronin** [comment]
Many thanks for the suggestions, Johann!

We should:

* convert virtual functions to **pure** virtual functions,
* determine/introspect the interfaces to see which is necessary 
* ADD documentations to virtual function!!!

With kind regards,

Hao
