### ISSUE TITLE
Error, warning and log messages handling

### ISSUE THREAD

**Issue by nojhan** [IOHprofiler/IOHexperimenter#60]
As of today, there's no modern handling of error or warning messages.
The entry point is in the [common](https://github.com/IOHprofiler/IOHexperimenter/blob/master/src/Template/IOHprofiler_common.cpp) file.

Problems of this approach are:
- The `IOH_error` function does `exit` the program, however, raising an exception may be easier to handle for higher layers, especially for bindings toward other languages.
- The `IOH_warning` and `IOH_log` output to `cout`, which breaks common assumptions.
- Only one `IOH_log` overload allows for a (hard-coded) redirection on another stream, which may pollute any embedding in an interactive tool.
- There is no log level management, which makes debugging difficult (incidentally, this may explain the lack of use of the log function?).
- The functions take a string, making it mandatory to forge a message prior to their call if one want to output a variable's value.

I suggest the following refactoring:
- Use the [clutchlog](https://github.com/nojhan/clutchlog) library (which I developed with IOH in mind).
- Allow to set up a default redirection to a file stream (for bindings).
- Raise an exception in `IOH_error`.
- Replace `IOH_warning` and `IOH_log` by a single `IOH_log` macro, taking a log level and a stream, which may be used as: `IOH_log(warning, "Maybe you don't want to have " << that_many << " objectives");`.
- Use the logging feature **a lot more** in the code to enable easier debugging.

**Comment by nojhan** [comment]
I propose to do this myself if it's OK with you.

**Comment by wangronin** [comment]
Dear Johann,

My apologies for the extremely late reply! Yes, it would be really great if you could implement this? Perhaps, you could show us an example and we could do it (feel bad if you it all by yourself..)

Thank you!

With kind regards,
Hao

**Comment by nojhan** [comment]
I will happily do my best to advance on that.

For the example, I set up an [example demo](https://github.com/nojhan/clutchlog/blob/master/tests/t-demo.cpp) or you can just look at the [clutchlog website](https://github.com/nojhan/clutchlog/blob/master/tests/t-demo.cpp) to get a grasp of all the features.

However, it would be tied up to `C++17`, is that a problem?
Note that switching to `C++17` would also have the advantage of bringing cleaner file system management (also avoiding some limitations of the current implementation).

**Comment by jacobdenobel** [comment]
Hi Johann,

Thank you for that! Please let us know if you need any help. I upgraded the lib to C++17 in the branch; 'restructure'. I would be nice if you could work from that branch from now on. Also, feel free to leave any comments on the restructuring part in that branch.

Thanks again!

**Comment by jdreo** [comment]
What would be the policy for using clutchlog within IOH? There is several options:

1.  copy/paste the (single) header in IOH source code and try not to forget to update if necessary;
2. add a Git submodule pointing to clutchlog;
3. let the user handle the dependency management.

**Comment by jacobdenobel** [comment]
Hi Johann, I'd prefer the second option, since this ensures that the code stays up to date, and also allows the user to clone the entire solution and dependencies in one go.
