### ISSUE TITLE
Default directories of csv logger cannot be created

### ISSUE THREAD

**Issue by nojhan** [IOHprofiler/IOHexperimenter#64]
If one instantiates a `csv_logger` with the empty constructor, the program crashes because it cannot create a hierarchy of directories.

Creating the top-level directory by hand solves the problem, but violates user expectations.

Using C++17's filesystem module instead of the adhoc functions in `IOHprofiler_csv_logger.cpp` would solve such problems.

**Comment by jacobdenobel** [comment]
Hi Johann, This is fixed in the branch restructure, which is pull request I am working on now. I also agree that using C++17, helped out a lot.
