### ISSUE TITLE
Pypi package error?

### ISSUE THREAD

**Issue by jrapin** [IOHprofiler/IOHexperimenter#75]
Hi,
IOHProfiler package seems to be broken:
`ERROR: Requested IOHexperimenter>=0.2.8 from https://files.pythonhosted.org/packages/83/9d/97995997158dd9bf80f8731fc4d3eaf4ebbf1e787505a48745a32e8744f0/IOHexperimenter-0.2.8r.tar.gz#sha256=837ba5e8844de28344bfde0810a19e6fa9e91ba9eddc11f19ac5be796f4db0a2 (from nevergrad==0.4.2.post2) has different version in metadata: '0.2.8'`

I recently got this error both on Windows and Ubuntu. Eg:
https://app.circleci.com/pipelines/github/jrapin/nevergrad/22/workflows/a953c962-8a90-4823-bdb3-f787d9399dd7/jobs/98

**Comment by jacobdenobel** [comment]
Hi, this should be fixed now. Please try to use version >=0.2.8.7

**Comment by jrapin** [comment]
Yes, it worked, thanks
