### ISSUE TITLE
Can't instantiate custom suite from configuration.ini

### ISSUE THREAD

**Issue by rickboks** [IOHprofiler/IOHexperimenter#77]
Hi, I have implemented a custom IOHprofiler_suite following the instructions at [the wiki](https://iohprofiler.github.io/IOHexp/extension/#adding-new-suites). Now I am trying to use it by passing the suite name to `suite_name` in `configuration.ini`. I first register the suite using the statement: 

`static registerInFactory<IOHprofiler_suite<double>,Random_suite> regSuite("RANDOM");`

"RANDOM" is the name of the suite. Now, I initialize the `IOHprofiler_experimenter` using:
`IOHprofiler_experimenter<double> experimenter(configFile,algorithm);`

This throws the error: `IOH_ERROR_INFO : Input value exceeds upperbound.`. I think this error is thrown because the suite is not registered correctly, because neither of the constructors of the suite is ever called. Also, instantiating the suite 'manually' like this does work: 
`std::shared_ptr<IOHprofiler_suite<double>> suite = genericGenerator<IOHprofiler_suite<double>>::instance().create("RANDOM");`

Am I doing something wrong, or is it not possible to instantiate custom suites via the configuration file? I have the latest version of IOHexperimenter installed. Thanks in advance!

**Comment by rickboks** [comment]
The problem is fixed by setting:
```
static int max_number_of_problem = std::numeric_limits<int>::max();
static int max_dimension = std::numeric_limits<int>::max();
```
in src/Template/Experiments/IOHprofiler_configuration.hpp. These values are only set for BBOB and PBO, and are 0 otherwise.

**Comment by wangronin** [comment]
@rickboks Many thanks for report the issue and the fix to it!
@FurongYe Could you kindly take a look into it?

With kind regards,
Hao

**Comment by FurongYe** [comment]
@rickboks , thanks for reporting the issue. Yes! Currently, the configuration file is only available for PBO and BBOB suite. As you did, it can be used for customized suites by modifying the IOHprofiler_configuration.h file. We will think about this case and provide more details in the instruction.
