### ISSUE TITLE
Problem with bounds

### ISSUE THREAD

**Issue by rickboks** [IOHprofiler/IOHexperimenter#78]
In `IOHprofiler_problem.hpp`, the functions `IOHprofiler_set_number_of_variables` set the entire upper/lowerbounds to their first values, cast to an integer. This does not allow for non-box constraints or real-valued bounds. For example, the bound [1.5, 2, 3.5] is changed to [1, 1, 1]. These lines are responsible (in both overloads):

```
if (this->lowerbound.size() != 0) {
  this->IOHprofiler_set_lowerbound(this->lowerbound[0]);
}
if (this->upperbound.size() != 0) {
  this->IOHprofiler_set_upperbound(this->upperbound[0]);
}
```
Removing these lines solved the problem for me.

**Comment by wangronin** [comment]
@FurongYe  Could you double-check this and see if we also need to change it in the new structure?
@rickboks Many thanks for reporting the issue!

**Comment by FurongYe** [comment]
@rickboks Thanks for reporting the issue. By default, the bounds of variables are the same for all indexes. If you define a problem in which bounds are different for each variable, please customize this in the virtual function 'prepare_problem'. All settings that will adjust with the dimension should be instantiated in the function. In this case, the values of bounds may change with dimensions.
