### ISSUE TITLE
Split tests executables

### ISSUE THREAD

**Issue by jdreo** [IOHprofiler/IOHexperimenter#84]
The current setup is to have a single executable which holds all the tests.

# Problem

This is not scalable. When one develop a new feature, one would expect to be able to do rapid build/test iterations, for instance by building only the related test(s). Having all in one place just makes the builds longer, reducing efficiency.
Additionally, when tests run are going to become longer, a similar problem will occur with runtimes. While being able to run only a targeted set of tests would also solve the problem.

# Suggested solution

Use a single executable target by test and let a test manager (like [CTest](https://gitlab.kitware.com/cmake/community/-/wikis/doc/ctest/Testing-With-CTest), as the project is using CMake anyway) allow for various test execution options (tests filtering patterns, parallel runs, code analysis integration, dashboard submissions, etc.).

**Comment by jdreo** [comment]
It would also be useful for debugging if one could look at the output of tests, which I'm not sure is easy to do right now with so many units.

**Comment by jacobdenobel** [comment]
What kind of output would you like to see?

I will take a closer look at test organization later. Note that in gtest you are able to [filter](https://github.com/google/googletest/blob/master/docs/advanced.md#running-a-subset-of-the-tests), and produce output reports for dashboard and ci.

**Comment by jdreo** [comment]
I would like to be able to do `cmake .. && make test_x && ./tests/test_x` rapidly.
Because I'm developing new features on a test exe (so that it's readily done).

As of today, I cannot build specific test targets, because there is a single `test_ioh` one, which has to be rebuilt every time, which makes me wait too much between two code iteration.

**Comment by jacobdenobel** [comment]
Closing this, PR #81 is merged, which adresses this issue.
