### ISSUE TITLE
Faster objective function value comparison

### ISSUE THREAD

**Issue by jdreo** [IOHprofiler/IOHexperimenter#91]
As of now, objective function value comparison goes through the `common::OptimizationType` enum, which is passed to functions like `compare_objectives`, where there is a test, which branch out on `operator<` or `operator>`.

The problem is that such comparisons are heavily used in the algorithm that computes the empirical attainment function.
Hence, having a test at each call is heavy on CPU.

It should be possible to optimize out the test by letting the `OptimizationType` holds a comparison operator, which would be directly used. Or use the the enum as a template parameter to specialize the comparison functions and let the compiler plug the good one.

Both options may restrict loggers to homogeneous problem sets.
In the first case, the virtual indirection may be not worth the test, so maybe the second option would be better.

**Comment by jacobdenobel** [comment]
In general I like the idea, only this would indeed constrict the loggers to homogeneous problems. This would also cause an introduction of an additional template parameter for Problems, and maybe also on the loggers. 

I think we should be carefull on how we would implement this, I will take a first look on how to aproach.
