### ISSUE TITLE
PointerReference nullptr issue on gcc

### ISSUE THREAD

**Issue by jacobdenobel** [IOHprofiler/IOHexperimenter#94]
The test: `store_properties` currently [fails](https://github.com/IOHprofiler/IOHexperimenter/runs/3303798309?check_suite_focus=true). 

It fails on the assertion that the (`first_eval`) value for:
```cpp
double* p_transient_att = nullptr;
watch::PointerReference attpr("Att_PtrRef", p_transient_att);
```
is a `std::nullopt`, if left unchanged, since the pointer it refers to is set to a `nullptr`.  When using other compilers (MSVC, Clang), this does not fail, and a `std::nullopt` is produced correctly. 

The `PointerReference` gets constructed properly, and `nullptr` gets assigned to `_variable`. However, when calling the call operator, the value for this pointer member `_variable`, is changed to some other random memory adress, which cause the logic in the method to produce a random double value for that adress, as we just cast the result. 

Since the field `_variable` is a protected member, I do not understand how its value can change outside the scope of the class body or its parents, but this still clearly happens. 

Another weird thing about the bug is, it that there is a way to supress it; By calling the property once with a default `logger::Info`, the value `_variable` remains to be a `nullptr`: 
```cpp
logger::Info info;
attpr(info);
```
The above is currently added to the test `store_properties` in order to ensure we pass the CI. 

(tagging @nojhan, @jdreo)

**Comment by jdreo** [comment]
Works on MacOS with g++ 11.2. What's your configuration?

**Comment by jacobdenobel** [comment]
Ubuntu 20.04 on WSL, with gcc: g 9.3.0. In the continous integration this also fails for gcc 8 on Ubuntu 20.04: https://github.com/IOHprofiler/IOHexperimenter/runs/3303798309?check_suite_focus=true
